[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "forge-std/=lib/forge-std/src/"
]

# Kairos Network Configuration
[rpc_endpoints]
kairos = "https://public-en-kairos.node.kaia.io"
kairos_testnet = "https://public-en-kairos.node.kaia.io"

[etherscan]
kairos = { key = "${KAIROS_API_KEY}", url = "https://kairoscan.io/api" }

# Gas settings for Kairos
[profile.kairos]
gas_limit = 30000000
gas_price = 1000000000  # 1 gwei

# Optimizer settings
optimizer = true
optimizer_runs = 200

# Solidity version
solc_version = "0.8.19"

# Via IR for better optimization
via_ir = true

# Additional settings for Kairos compatibility
allow_paths = ["contracts", "lib"]
auto_detect_solc = false